# Generated by Django 4.2.2 on 2023-06-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration', models.IntegerField()),
                ('vote_king', models.IntegerField()),
                ('vote_queen', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
