# Generated by Django 4.2.2 on 2023-06-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_voters_vote_king_alter_voters_vote_queen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='vote_king',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voters',
            name='vote_queen',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
