# Generated by Django 4.2.2 on 2023-06-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_voters_vote_king_alter_voters_vote_queen'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
