# Generated by Django 4.2.2 on 2023-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_candidates_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='path_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
