# Generated by Django 4.2.2 on 2023-06-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_candidates_id_alter_voters_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='registration',
        ),
    ]
