# Generated by Django 4.2.2 on 2023-06-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_candidates_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
