# Generated by Django 4.2.2 on 2023-06-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_voters_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='status',
            field=models.BooleanField(),
        ),
    ]
